package com.example.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage(val code: String, val displayName: String, val isRtl: Boolean) {
    FA("fa", "فارسی", true),
    EN("en", "English", false);

    companion object {
        fun fromCode(code: String?): AppLanguage =
            entries.firstOrNull { it.code.equals(code, ignoreCase = true) } ?: FA
    }
}

data class LocalizedStrings(
    val language: AppLanguage,
    val appTitle: String,
    val studioSubtitle: String,
    val tabDirector: String,
    val tabVault: String,
    val tabCode: String,
    val apiKeyActiveBtn: String,
    val apiKeySetBtn: String,
    val apiKeyBannerConfiguredTitle: (String) -> String,
    val apiKeyBannerUnconfiguredTitle: String,
    val apiKeyBannerConfiguredSub: String,
    val apiKeyBannerUnconfiguredSub: String,
    val editAction: String,
    val savePermanentAction: String,
    val monitorPollingStatus: String,
    val monitorPlaybackReady: (String) -> String,
    val monitorStandby: String,
    val waitingForVideoMsg: String,
    val elapsedAndNextPoll: (String, Int) -> String,
    val cancelPollingCta: String,
    val rollCameraCta: String,
    val targetOutputLabel: (String) -> String,
    val presetsHeader: String,
    val restoreDefaultPrompt: String,
    val spokenDialogueCuesTitle: String,
    val spokenDialogueCuesSubtitle: String,
    val addCueButton: String,
    val characterLabel: String,
    val vocalDeliveryLabel: String,
    val spokenLineLabel: String,
    val insertIntoPromptCta: String,
    val promptSectionTitle: String,
    val promptPlaceholder: String,
    val aiPolishDialogueCta: String,
    val quickCameraModifiersLabel: String,
    val operationAndDownloadConfigTitle: String,
    val veoModelLabel: String,
    val autoFallback429Label: String,
    val autoFallback429Sub: String,
    val aspectRatioLabel: String,
    val resolutionLabel: String,
    val outputFilenameLabel: String,
    val generateAndDownloadCta: (String) -> String,
    val pollingInProgressCta: (Int) -> String,
    val sdkLogsLink: String,
    val securityNoticeText: String,
    val emptyVaultTitle: String,
    val emptyVaultSubtitle: String,
    val openDirectorStudioCta: String,
    val recordedTakesHeader: String,
    val recordedTakesSub: (Int) -> String,
    val playBtn: String,
    val saveToMoviesBtn: String,
    val usePromptBtn: String,
    val liveConsoleTitle: String,
    val liveConsoleSub: String,
    val clearConsoleBtn: String,
    val liveCodeSyncTitle: String,
    val copyCodeBtn: String,
    val copiedBtn: String,
    val apiKeyDialogTitle: String,
    val apiKeyDialogDescription: String,
    val apiKeyInputLabel: String,
    val backupApiKeyInputLabel: String,
    val clearSavedKeyBtn: String,
    val confirmSavePermanentBtn: String,
    val cancelBtn: String
)

val PersianStrings = LocalizedStrings(
    language = AppLanguage.FA,
    appTitle = "استودیو دیالوگ Veo",
    studioSubtitle = "ساخت ویدیو و دیالوگ سینمایی با مدل Veo 3.1",
    tabDirector = "استودیو کارگردان",
    tabVault = "آرشیو برداشت‌ها",
    tabCode = "کنسول و کد SDK",
    apiKeyActiveBtn = "کلید فعال",
    apiKeySetBtn = "کلید API",
    apiKeyBannerConfiguredTitle = { masked -> "کلید API دائمی فعال است ($masked)" },
    apiKeyBannerUnconfiguredTitle = "تنظیم دائمی کلید Gemini API (الزامی برای ساخت ویدیو)",
    apiKeyBannerConfiguredSub = "پشتیبانی از تلاش مجدد خودکار ضد خطای HTTP 429 • برای ویرایش ضربه بزنید",
    apiKeyBannerUnconfiguredSub = "یک‌بار کلید خود را وارد کنید تا برای همیشه در حافظه برنامه ذخیره شود",
    editAction = "ویرایش",
    savePermanentAction = "ثبت دائمی",
    monitorPollingStatus = "در حال استعلام عملیات (POLLING)",
    monitorPlaybackReady = { file -> "آماده پخش • $file" },
    monitorStandby = "مانیتور کارگردان • آماده به کار",
    waitingForVideoMsg = "در حال انتظار برای تکمیل رندر ویدیو...",
    elapsedAndNextPoll = { elapsed, nextSec -> "زمان سپری‌شده: $elapsed • بررسی بعدی در ${nextSec} ثانیه" },
    cancelPollingCta = "لغو عملیات",
    rollCameraCta = "شروع فیلم‌برداری",
    targetOutputLabel = { file -> "فایل خروجی: $file" },
    presetsHeader = "صحنه‌ها و دیالوگ‌های آماده",
    restoreDefaultPrompt = "بازگردانی پرامپت پیش‌فرض",
    spokenDialogueCuesTitle = "نوبت‌های دیالوگ گفتاری",
    spokenDialogueCuesSubtitle = "مدل Veo 3.1 جملات داخل تک‌کوتیشن ('...') را با لب‌خوانی دقیق تولید می‌کند",
    addCueButton = "افزودن دیالوگ",
    characterLabel = "شخصیت (مثلاً A man)",
    vocalDeliveryLabel = "لحن بیان (مثلاً murmurs)",
    spokenLineLabel = "متن دیالوگ گفتاری",
    insertIntoPromptCta = "افزودن به پرامپت",
    promptSectionTitle = "پرامپت صحنه و دیالوگ",
    promptPlaceholder = "زاویه دوربین، نورپردازی و دیالوگ شخصیت‌ها را در تک‌کوتیشن بنویسید...",
    aiPolishDialogueCta = "بهبود هوشمند با AI",
    quickCameraModifiersLabel = "افزودن سریع تنظیمات دوربین و نورپردازی:",
    operationAndDownloadConfigTitle = "تنظیمات مدل Veo 3.1 و خروجی فایل",
    veoModelLabel = "انتخاب مدل Veo",
    autoFallback429Label = "محافظ هوشمند خطای HTTP 429 (تلاش مجدد و جایگزینی مدل)",
    autoFallback429Sub = "در صورت محدودیت سهمیه (429)، برنامه به‌طور خودکار مکث کرده و مدل‌های جایگزین Veo یا کلید دوم را امتحان می‌کند",
    aspectRatioLabel = "نسبت تصویر",
    resolutionLabel = "کیفیت ویدیو",
    outputFilenameLabel = "نام فایل دانلودی (MP4)",
    generateAndDownloadCta = { path -> "ساخت و دانلود ویدیو ($path)" },
    pollingInProgressCta = { sec -> "در حال ساخت ویدیو (${sec} ثانیه)..." },
    sdkLogsLink = "مشاهده لاگ‌ها <-",
    securityNoticeText = "نکته امنیتی: کلید API شما به صورت دائمی در حافظه امن داخلی برنامه ذخیره می‌شود. همچنین می‌توانید چند کلید را برای چرخش خودکار در برابر خطای 429 ثبت کنید.",
    emptyVaultTitle = "هنوز ویدیویی ساخته نشده است",
    emptyVaultSubtitle = "اولین ویدیوی دیالوگ‌دار خود را از تب «استودیو کارگردان» بسازید. فایل‌های MP4 دانلودشده در این قسمت ذخیره می‌شوند.",
    openDirectorStudioCta = "ورود به استودیو کارگردان",
    recordedTakesHeader = "برداشت‌های ضبط‌شده و تاریخچه عملیات",
    recordedTakesSub = { count -> "$count رکورد ذخیره‌شده در دیتابیس محلی Room" },
    playBtn = "پخش",
    saveToMoviesBtn = "ذخیره در گالری",
    usePromptBtn = "استفاده از پرامپت",
    liveConsoleTitle = "کنسول زنده وضعیت عملیات (Telemetry)",
    liveConsoleSub = "گزارش لحظه‌ای استعلام ۱۰ ثانیه‌ای و مدیریت خطای 429",
    clearConsoleBtn = "پاک کردن",
    liveCodeSyncTitle = "نمایشگر کد زنده Veo 3.1",
    copyCodeBtn = "کپی کد",
    copiedBtn = "کپی شد!",
    apiKeyDialogTitle = "تنظیم دائمی کلید Gemini API",
    apiKeyDialogDescription = "کلید اصلی Gemini API خود را وارد کنید. همچنین برای جلوگیری از خطای HTTP 429 (محدودیت تعداد درخواست)، می‌توانید در کادر دوم یک کلید پشتیبان وارد کنید تا در صورت پر شدن سهمیه کلید اول، برنامه به‌طور خودکار از کلید دوم استفاده کند.",
    apiKeyInputLabel = "کلید اصلی Gemini API (AIza...)",
    backupApiKeyInputLabel = "کلید پشتیبان اختیاری (برای چرخش خودکار در خطای 429)",
    clearSavedKeyBtn = "حذف کلیدهای ذخیره‌شده",
    confirmSavePermanentBtn = "ذخیره دائمی",
    cancelBtn = "انصراف"
)

val EnglishStrings = LocalizedStrings(
    language = AppLanguage.EN,
    appTitle = "Veo Dialogue Studio",
    studioSubtitle = "Veo 3.1 Cinematic Video & Dialogue Generator",
    tabDirector = "Director Studio",
    tabVault = "Takes Vault",
    tabCode = "SDK & Telemetry",
    apiKeyActiveBtn = "Key Active",
    apiKeySetBtn = "API Key",
    apiKeyBannerConfiguredTitle = { masked -> "Permanent API Key Active ($masked)" },
    apiKeyBannerUnconfiguredTitle = "Set Permanent Gemini API Key (Required for Video Gen)",
    apiKeyBannerConfiguredSub = "Smart HTTP 429 auto-retry & fallback enabled • Tap to edit",
    apiKeyBannerUnconfiguredSub = "Enter your API key once to save it permanently on your device",
    editAction = "Edit",
    savePermanentAction = "Set Key",
    monitorPollingStatus = "POLLING OPERATION",
    monitorPlaybackReady = { file -> "PLAYBACK READY • $file" },
    monitorStandby = "DIRECTOR MONITOR • STANDBY",
    waitingForVideoMsg = "Waiting for video generation to complete...",
    elapsedAndNextPoll = { elapsed, nextSec -> "Elapsed: $elapsed • Next check in ${nextSec}s" },
    cancelPollingCta = "Cancel Polling",
    rollCameraCta = "Roll Camera",
    targetOutputLabel = { file -> "Target output: $file" },
    presetsHeader = "SCENE & DIALOGUE PRESETS",
    restoreDefaultPrompt = "Restore Default Prompt",
    spokenDialogueCuesTitle = "Spoken Dialogue Cues",
    spokenDialogueCuesSubtitle = "Veo 3.1 synthesizes lip-synced speech from single-quoted lines",
    addCueButton = "Add Cue",
    characterLabel = "Character",
    vocalDeliveryLabel = "Vocal Delivery",
    spokenLineLabel = "Spoken Line (wrapped in '...' automatically)",
    insertIntoPromptCta = "Insert into Prompt",
    promptSectionTitle = "Scene & Dialogue Prompt",
    promptPlaceholder = "Describe camera framing, lighting, and character dialogue in single quotes…",
    aiPolishDialogueCta = "AI Polish Dialogue",
    quickCameraModifiersLabel = "Quick Camera & Lighting Modifiers:",
    operationAndDownloadConfigTitle = "Veo 3.1 Operation & Download Config",
    veoModelLabel = "Veo Model",
    autoFallback429Label = "Smart HTTP 429 Guard (Auto-Retry & Model Fallback)",
    autoFallback429Sub = "Automatically backs off on HTTP 429 rate limits and falls back across Veo models or backup API key",
    aspectRatioLabel = "Aspect Ratio",
    resolutionLabel = "Resolution",
    outputFilenameLabel = "Output Download Path",
    generateAndDownloadCta = { path -> "Generate & Download ($path)" },
    pollingInProgressCta = { sec -> "Polling Veo 3.1 Operation (${sec}s)..." },
    sdkLogsLink = "SDK Logs ->",
    securityNoticeText = "Security Note: Your API key is stored permanently in private app storage. You can also configure a backup key for automatic rotation on HTTP 429.",
    emptyVaultTitle = "No Generated Takes Yet",
    emptyVaultSubtitle = "Generate your first Veo 3.1 dialogue video from the Director Studio tab. Completed takes and local MP4 files will appear here.",
    openDirectorStudioCta = "Open Director Studio",
    recordedTakesHeader = "Recorded Takes & Operations",
    recordedTakesSub = { count -> "$count local Room DB record(s) • Saved MP4 files" },
    playBtn = "Play",
    saveToMoviesBtn = "Movies",
    usePromptBtn = "Use Prompt",
    liveConsoleTitle = "Live Operation Polling Console",
    liveConsoleSub = "10,000ms interval getVideosOperation logs & 429 retry telemetry",
    clearConsoleBtn = "Clear",
    liveCodeSyncTitle = "Live Veo 3.1 Code Sync",
    copyCodeBtn = "Copy Code",
    copiedBtn = "Copied!",
    apiKeyDialogTitle = "Permanent Gemini API Key Setup",
    apiKeyDialogDescription = "Enter your primary Gemini API Key (AIza...). To prevent HTTP 429 quota errors, you can also provide an optional backup API key for automatic key rotation.",
    apiKeyInputLabel = "Primary Gemini API Key (AIza...)",
    backupApiKeyInputLabel = "Optional Backup API Key (Auto-rotates on HTTP 429)",
    clearSavedKeyBtn = "Clear Saved Keys",
    confirmSavePermanentBtn = "Save Permanently",
    cancelBtn = "Cancel"
)

val LocalAppStrings = staticCompositionLocalOf { PersianStrings }
